// <auto-generated />
using System;
using FD_Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FD_Service.Migrations
{
    [DbContext(typeof(FDDBContext))]
    [Migration("20240703123741_UpdateFDDetailsPercentageCol")]
    partial class UpdateFDDetailsPercentageCol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FD_Service.Model.CustomerFDDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("FDDetailsId")
                        .HasColumnType("int");

                    b.Property<double>("MaturityAmount")
                        .HasColumnType("float");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FDDetailsId");

                    b.ToTable("CustomerFDDetails");
                });

            modelBuilder.Entity("FD_Service.Model.FDDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FDPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Year")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FDDetails");
                });

            modelBuilder.Entity("FD_Service.Model.CustomerFDDetails", b =>
                {
                    b.HasOne("FD_Service.Model.FDDetails", null)
                        .WithMany("CustomerFDDetails")
                        .HasForeignKey("FDDetailsId");
                });

            modelBuilder.Entity("FD_Service.Model.FDDetails", b =>
                {
                    b.Navigation("CustomerFDDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
